### ISSUE TITLE
Twitter API follower response limited to 5000 ids

### ISSUE THREAD

**Issue by jbayer** [andypiper/sinatra-cf-twitter#1]
Twitter might be limiting the ids of the followers it returns. When I do this one it works:
http://jambayfollows.cloudfoundry.com/follows?user1=gnanaseelan&user2=jambay

Notice that gnanaseelan is only following 37 people, but if you follow someone following more people, then it seems like it doesn't work.

So then I did this:

```
def is_following?(a,b)
    followers = Twitter.follower_ids(twitter_id(b)).ids
    puts b + ' ' + followers.length.to_s
    followers.include?(twitter_id(a))
end
```

And got this result in the logs:

cloudfoundry 5000

Which means that twitter limits the results to 5000 followers b/c CF has about ~15K+

**Comment by andypiper** [comment]
Yeah, there's really nothing simple to do about this and this was designed as a simple demo. For now, I've documented the limitation in the README -- thanks for the heads up, I'd completely missed it.
